"""Added column avatar_url in users_data table

Revision ID: 8b9c605f6a12
Revises: f0ead78decfb
Create Date: 2025-12-13 18:11:34.873246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9c605f6a12'
down_revision: Union[str, Sequence[str], None] = 'f0ead78decfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_data', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_data', 'avatar_url')
    # ### end Alembic commands ###
