"""added column "score" for players and type of a match

Revision ID: 3b9b6edb223f
Revises: 6b1cb2db474d
Create Date: 2025-12-05 00:58:57.373944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9b6edb223f'
down_revision: Union[str, Sequence[str], None] = '6b1cb2db474d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('type', sa.String(), nullable=False))
    op.add_column('matches', sa.Column('player1_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('player2_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'player2_score')
    op.drop_column('matches', 'player1_score')
    op.drop_column('matches', 'type')
    # ### end Alembic commands ###
