"""Create table: user_auth, user_data, match, match_sets

Revision ID: 6b1cb2db474d
Revises: 
Create Date: 2025-12-05 00:03:07.351929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1cb2db474d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_auth')),
    sa.UniqueConstraint('login', name=op.f('uq_users_auth_login'))
    )
    op.create_table('users_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users_auth.id'], name=op.f('fk_users_data_id_users_auth')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_data'))
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users_data.id'], name=op.f('fk_matches_player1_id_users_data')),
    sa.ForeignKeyConstraint(['player2_id'], ['users_data.id'], name=op.f('fk_matches_player2_id_users_data')),
    sa.ForeignKeyConstraint(['winner_id'], ['users_data.id'], name=op.f('fk_matches_winner_id_users_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_table('match_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('player1_score', sa.Integer(), nullable=False),
    sa.Column('player2_score', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_sets_match_id_matches')),
    sa.ForeignKeyConstraint(['winner_id'], ['users_data.id'], name=op.f('fk_match_sets_winner_id_users_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_sets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_sets')
    op.drop_table('matches')
    op.drop_table('users_data')
    op.drop_table('users_auth')
    # ### end Alembic commands ###
