"""Added new table UserStats

Revision ID: a27638849fd3
Revises: e6d5889591c4
Create Date: 2025-12-08 18:15:50.978094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27638849fd3'
down_revision: Union[str, Sequence[str], None] = 'e6d5889591c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amateur_games_count', sa.Integer(), nullable=False),
    sa.Column('tournament_games_count', sa.Integer(), nullable=False),
    sa.Column('wins_count', sa.Integer(), nullable=False),
    sa.Column('losses_count', sa.Integer(), nullable=False),
    sa.Column('average_match_duration', sa.Integer(), nullable=False),
    sa.Column('average_time_to_point', sa.Integer(), nullable=False),
    sa.Column('total_matches_duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users_data.id'], name=op.f('fk_users_stats_id_users_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_stats'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_stats')
    # ### end Alembic commands ###
