"""Made property /middle_name/ of table users_data nullable

Revision ID: f0ead78decfb
Revises: a27638849fd3
Create Date: 2025-12-13 16:02:29.293341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ead78decfb'
down_revision: Union[str, Sequence[str], None] = 'a27638849fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_data', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_data', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
