"""Added new table roles

Revision ID: d145ac8420b6
Revises: 8b9c605f6a12
Create Date: 2025-12-14 20:25:22.885525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd145ac8420b6'
down_revision: Union[str, Sequence[str], None] = '8b9c605f6a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.add_column('users_auth', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_auth_role_id_roles'), 'users_auth', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_auth_role_id_roles'), 'users_auth', type_='foreignkey')
    op.drop_column('users_auth', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
