"""Schange column name in table matches

Revision ID: 263beb8fae70
Revises: 3560e1265b6b
Create Date: 2025-12-18 16:42:37.504444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '263beb8fae70'
down_revision: Union[str, Sequence[str], None] = '3560e1265b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.drop_column('matches', 'date')
    op.alter_column('users_auth', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_auth', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('matches', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('matches', 'datetime')
    # ### end Alembic commands ###
