"""added column "status" for table matches

Revision ID: 78c0f7d4cd63
Revises: 263beb8fae70
Create Date: 2025-12-23 02:59:10.293258

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78c0f7d4cd63"
down_revision: Union[str, Sequence[str], None] = "263beb8fae70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

match_status_enum = sa.Enum(
    "IN_PROGRESS", "FINISHED", "CANCELED", "REGISTERED", name="match_status"
)


def upgrade() -> None:
    """Upgrade schema."""
    match_status_enum.create(op.get_bind())

    op.add_column(
        "matches", sa.Column("status", match_status_enum, nullable=False, default="REGISTERED")
    )

    op.alter_column(
        "matches",
        "status",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "status")
    match_status_enum.drop(op.get_bind())
