"""added column duration in match

Revision ID: e6d5889591c4
Revises: 3b9b6edb223f
Create Date: 2025-12-05 02:28:31.196922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d5889591c4'
down_revision: Union[str, Sequence[str], None] = '3b9b6edb223f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('duration_in_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'duration_in_minutes')
    # ### end Alembic commands ###
